### ISSUE TITLE
Allow to start a video at a given time 

### ISSUE THREAD

**Issue by markets** [markets/suchtube#3]
Something similar to `?t=30` that YouTube allows.

Since we're using the YouTube API (docs: https://developers.google.com/youtube/v3/docs/search), check if this param can be injected in the API call, otherwise we can just append `?t=30` to the final link.

**Comment by markets** [comment]
@pcirujeda do you want to help on this one? 😛

**Comment by pcirujeda** [comment]
![](http://img.izismile.com/img/img5/20121020/1000/not_so_impressive_now_24.gif)
